### ISSUE TITLE
Tilt+Tap does not work on HTML5 standalone

### ISSUE THREAD

**Issue by goethel** [worzalla/MinigameDungeon#42]
### Description
When playing a minigame on HTML5 with laptop (see build description). Tilt + Tap minigames (or at least ones described as being tilt+tap on the game UI) do not work with laptops. I noticed that the arrow keys still work however, but this is not communicated

### Severity

Low

### Suggestions

disable the graphics displaying Tilt+Tap on the PC/ unity web application, and add a Left Mouse Click + WASD icon

### Build Info

v0.2.1, HTML5 version, Google Chrome, MacOS 10.15

**Comment by worzalla** [comment]
This is resolved by building to Android.
