### ISSUE TITLE
PC/Laptop control scheme images do not relate

### ISSUE THREAD

**Issue by goethel** [worzalla/MinigameDungeon#43]
### Description
When playing a minigame with the PC standalone version/ not on a mobile device, the prompts for the controls on each aren't immediately obvious to a user.  Example: Tap meaning left mouse click, Swipe meaning click and drag mouse, etc

### Severity
Trivial/Enhancement

### Suggestions

Add identifying code to get users setup (probably through useragent I imagine), and then switch the control help images with a PC version.

### Build Info

v0.2.1, HTML5 version, Google Chrome, MacOS 10.15

**Comment by worzalla** [comment]
This is resolved by building to Android.
