### ISSUE TITLE
Error on loading itch.io version on Safari Browser

### ISSUE THREAD

**Issue by goethel** [worzalla/MinigameDungeon#45]
### Description

I am receiving an error on initial Page load, while unityLoader is doing its thing

>[Error] WebGL: INVALID_OPERATION: texImage2D: type HALF_FLOAT_OES but ArrayBufferView is not NULL
	texImage2D
	_glTexImage2D (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:272693)
	wasm-stub
	<?>.wasm-function[6767]
	<?>.wasm-function[7104]
	<?>.wasm-function[7099]
	<?>.wasm-function[6415]
	<?>.wasm-function[8201]
	<?>.wasm-function[8328]
	<?>.wasm-function[8287]
	<?>.wasm-function[12220]
	<?>.wasm-function[12207]
	<?>.wasm-function[12187]
	<?>.wasm-function[10358]
	<?>.wasm-function[10345]
	<?>.wasm-function[10323]
	<?>.wasm-function[10188]
	<?>.wasm-function[10187]
	wasm-stub
	_main
	(anonymous function) (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:418224)
	callMain (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:448561)
	doRun (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:449237)
	run (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:449410)
	runCaller (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:448183)
	removeRunDependency (blob:https://v6p9d9t4.ssl.hwcdn.net/c6bbaacd-8d68-4abe-8d13-3bac79f8fab5:8:28408)
	processDataJob (UnityLoader.js:4:5441)
	(anonymous function) (UnityLoader.js:3:19248)
	(anonymous function)

I have checked with the Chrome browser, and I am not seeing any differences in the games ability to render, so I'm not sure if this is a problem or not

### Severity

Low, this could be an issue with unity web and safari, but I am not 100% sure

### Suggestions

If this is an issue with Safari, maybe include something somewhere in the game description or platforms, that Safari is not a supported browser.

### Build info
itch.io version
Safari 13.0.2
MacOS 10.15

**Comment by worzalla** [comment]
This is resolved by building to Android.
