### ISSUE TITLE
Drain the Water

### ISSUE THREAD

**Issue by willbrav** [worzalla/MinigameDungeon#49]
**Description**
While playing the water minigame, the water does not need to be drained in order to successfully complete the level

**Severity**
Low,  the level runs smoothly, and I can only replicate the issue by leaving a small amount of water at the bottom of the screen

**Suggestions**
Review edge cases for water entity

**Build Info**
android.apk version
Google Pixel 1
Android 10.0

**Comment by worzalla** [comment]
This is intentional. The success condition is actually the position of the player's head. If the water is under the player's head you will pass because you saved the adventurer from drowning.
